// Code generated by log-gen. DO NOT EDIT.
package logx

import (
	"go.uber.org/zap"
)

func Desugar() *zap.Logger {
	return getSugarLogger().Desugar()
}

func Named(name string) *zap.SugaredLogger {
	return getSugarLogger().Named(name)
}

func With(args ...interface{}) *zap.SugaredLogger {
	return getSugarLogger().With(args...)
}

func Debug(args ...interface{}) {
	getSugarLogger().Debug(args...)
}

func Info(args ...interface{}) {
	getSugarLogger().Info(args...)
}

func Warn(args ...interface{}) {
	getSugarLogger().Warn(args...)
}

func Error(args ...interface{}) {
	getSugarLogger().Error(args...)
}

func DPanic(args ...interface{}) {
	getSugarLogger().DPanic(args...)
}

func Panic(args ...interface{}) {
	getSugarLogger().Panic(args...)
}

func Fatal(args ...interface{}) {
	getSugarLogger().Fatal(args...)
}

func Debugf(template string, args ...interface{}) {
	getSugarLogger().Debugf(template, args...)
}

func Infof(template string, args ...interface{}) {
	getSugarLogger().Infof(template, args...)
}

func Warnf(template string, args ...interface{}) {
	getSugarLogger().Warnf(template, args...)
}

func Errorf(template string, args ...interface{}) {
	getSugarLogger().Errorf(template, args...)
}

func DPanicf(template string, args ...interface{}) {
	getSugarLogger().DPanicf(template, args...)
}

func Panicf(template string, args ...interface{}) {
	getSugarLogger().Panicf(template, args...)
}

func Fatalf(template string, args ...interface{}) {
	getSugarLogger().Fatalf(template, args...)
}

func Debugw(msg string, keysAndValues ...interface{}) {
	getSugarLogger().Debugw(msg, keysAndValues...)
}

func Infow(msg string, keysAndValues ...interface{}) {
	getSugarLogger().Infow(msg, keysAndValues...)
}

func Warnw(msg string, keysAndValues ...interface{}) {
	getSugarLogger().Warnw(msg, keysAndValues...)
}

func Errorw(msg string, keysAndValues ...interface{}) {
	getSugarLogger().Errorw(msg, keysAndValues...)
}

func DPanicw(msg string, keysAndValues ...interface{}) {
	getSugarLogger().DPanicw(msg, keysAndValues...)
}

func Panicw(msg string, keysAndValues ...interface{}) {
	getSugarLogger().Panicw(msg, keysAndValues...)
}

func Fatalw(msg string, keysAndValues ...interface{}) {
	getSugarLogger().Fatalw(msg, keysAndValues...)
}

func Sync() error {
	return getSugarLogger().Sync()
}
